"""add upload_picture

Revision ID: 4775899d7921
Revises: 2c195cb3413f
Create Date: 2016-10-07 11:18:42.662591

"""

# revision identifiers, used by Alembic.
revision = '4775899d7921'
down_revision = '2c195cb3413f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('upload_picture', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'upload_picture')
    ### end Alembic commands ###
