"""add body_html

Revision ID: 7dcc8e0f8269
Revises: a8efdf2468f7
Create Date: 2016-10-06 12:00:20.461189

"""

# revision identifiers, used by Alembic.
revision = '7dcc8e0f8269'
down_revision = 'a8efdf2468f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
